/* class-validator 에서 사용하는 상수 */
export const VALIDATION_CONSTANTS = {
    IsArray: "$target 의 $property 은/는 배열이어야 합니다.",
    IsBoolean: "$target 의 $property 은/는 boolean 값이어야 합니다.",
    IsDate: "$target 의 $property 은/는 날짜여야 합니다.",
    IsDateString: "$target 의 $property 은/는 날짜 문자열이어야 합니다.",
    IsEmail: "$target 의 $property 은/는 이메일이어야 합니다.",
    IsPassword: "$target 의 $property 은/는 비밀번호 형식이어야 합니다.",
    IsEnum: "$target 의 $property 은/는 유효한 값이어야 합니다.",
    IsInt: "$target 의 $property 은/는 정수이어야 합니다.",
    IsJSON: "$target 의 $property 은/는 JSON이어야 합니다.",
    IsNegative: "$target 의 $property 은/는 음수여야 합니다.",
    IsNotEmpty: "$target 의 $property 은/는 필수값입니다.",
    IsNotEmptyArray: "$target 의 $property 은/는 빈 배열일 수 없습니다.",
    IsNotEmptyObject: "$target 의 $property 은/는 빈 객체일 수 없습니다.",
    IsNotEmptyString: "$target 의 $property 은/는 빈 문자열일 수 없습니다.",
    IsNotEmptyObjectArray: "$target 의 $property 은/는 빈 객체의 배열일 수 없습니다.",
    IsNotEmptyStringArray: "$target 의 $property 은/는 빈 문자열의 배열일 수 없습니다.",
    IsNumber: "$target 의 $property 은/는 숫자이어야 합니다.",
    IsOptional: "$target 의 $property 은/는 선택적이어야 합니다.",
    IsPhoneNumber: "$target 의 $property 은/는 전화번호여야 합니다.",
    IsPositive: "$target 의 $property 은/는 양수여야 합니다.",
    IsString: "$target 의 $property 은/는 문자열이어야 합니다.",
    IsUrl: "$target 의 $property 은/는 URL이어야 합니다.",
    IsUUID: "$target 의 $property 은/는 UUID여야 합니다.",
    IsIn: "$target 의 $property 은/는 $constraint1여야 합니다.",
    IsFutureDate: "$target 의 $property 은/는 미래의 날짜여야 합니다.",
    Matches: "$target 의 $property 은/는 형식이 일치해야 합니다.",
    MaxLength: "$target 의 $property 은/는 최대 $constraint1 글자여야 합니다.",
    MinLength: "$target 의 $property 은/는 최소 $constraint1 글자여야 합니다.",
    ContainsType: "$target 의 $property 의 형식이 불일치합니다.",
    ArrayMinSize: "$target 의 $property 의 최소 $constraint1의 요소가 필요합니다.",
    ArrayMaxSize: "$target 의 $property 의 최대 $constraint1의 요소를 가질 수 있습니다.",
    ArrayUnique: "$target 의 $property 는 고유한 값이여야 합니다.",
    Max: "$target 의 $property 는 $constraint1 이하의 값이여야 합니다.",
    Min: "$target 의 $property 는 $constraint1 이상 값이여야 합니다.",
    IsRegex: "$target 의 $property 값은 유효하지 않습니다.",
    IsEmpty: "$property 의 값은 공백이 될 수 없습니다.",
    IsOrder: "$target 의 $property 값dl 유효하지 않습니다. (ASC|DESC)",
    IsTarget: "$target 의 $property 값dl 유효하지 않습니다. (all|level|user)",
    HasValue: "$property 이 존재해야 합니다.",
    IsMaxDiscount: "$property 값은 100 이상으로 설절할 수 없습니다.",
    IsMinDiscount: "$property 값은 0 이하로 설정할 수 없습니다.",
    RequireDiscount: "discountRage 와 discountPrice 는 동시에 존재할 수 없습니다.",
    IsBenefit: "$target 의 $property 값은 유효하지 않습니다. (POINT|COUPON)",
    InvalidUpdate: "$property 은/는 수정 대상이 아닙니다.",
    KeywordType: "$target 의 $property 값은 유효하지 않습니다. (all|name|phone|email)",
    IsYN: "$target 의 $property 값은 유효하지 않습니다. (y|n)",
};
